import 'dart:io';

// Generate PostgreSQL character classes from the same Dart Unicode rules used
// by CustomerIdentity. This keeps SQL validation independent of DB locales.
String ranges(RegExp expression) {
  final values = <String>[];
  int? start;
  for (var rune = 0; rune <= 0x110000; rune++) {
    final matches =
        rune < 0x110000 && expression.hasMatch(String.fromCharCode(rune));
    if (matches && start == null) start = rune;
    if (!matches && start != null) {
      values.add('[$start,$rune)');
      start = null;
    }
  }
  return '{${values.join(',')}}';
}

void main() {
  final letters = ranges(RegExp(r'^\p{L}$', unicode: true));
  final marks = ranges(RegExp(r'^\p{M}$', unicode: true));
  final whitespace = ranges(RegExp(r'^\s$', unicode: true));
  final header =
      '''-- Generated by scripts/generate_customer_name_policy.dart.
-- Uses Dart Unicode character classes, rather than locale-dependent SQL regexes.
-- Apply after migrations 001 and 002; no existing profile values are rewritten.
begin;

create or replace function repairshop_private.normalize_customer_name(p_value text)
returns text language plpgsql immutable parallel safe set search_path = ''
as \$\$
declare
  v_character text; v_result text := ''; v_space boolean := false;
  v_whitespace constant int4multirange := '$whitespace';
begin
  if p_value is null then return null; end if;
  for v_index in 1..pg_catalog.char_length(p_value) loop
    v_character := pg_catalog.substr(p_value, v_index, 1);
    if v_whitespace @> pg_catalog.ascii(v_character) then
      if v_result <> '' then v_space := true; end if;
    else
      if v_space then v_result := v_result || ' '; end if;
      v_result := v_result || v_character;
      v_space := false;
    end if;
  end loop;
  return v_result;
end;
\$\$;

create or replace function repairshop_private.customer_name_is_valid(p_value text)
returns boolean language plpgsql immutable parallel safe set search_path = ''
as \$\$
declare
  v_name text; v_code integer; v_letter boolean := false;
  v_mark_allowed boolean := false;
  v_letters constant int4multirange := '$letters';
  v_marks constant int4multirange := '$marks';
begin
  if p_value is null then return false; end if;
  -- Reject controls before normalizing whitespace, matching the mobile policy.
  for v_index in 1..pg_catalog.char_length(p_value) loop
    v_code := pg_catalog.ascii(pg_catalog.substr(p_value, v_index, 1));
    if v_code < 32 or v_code between 127 and 159 then return false; end if;
  end loop;
  v_name := repairshop_private.normalize_customer_name(p_value);
  if v_name = '' or pg_catalog.char_length(v_name) > 100 then return false; end if;
  for v_index in 1..pg_catalog.char_length(v_name) loop
    v_code := pg_catalog.ascii(pg_catalog.substr(v_name, v_index, 1));
    if v_letters @> v_code then
      v_letter := true;
      v_mark_allowed := true;
    elsif v_marks @> v_code then
      if not v_mark_allowed then return false; end if;
    elsif v_code in (32, 39, 45, 46, 8216, 8217) then
      v_mark_allowed := false;
    else
      return false;
    end if;
  end loop;
  return v_letter;
end;
\$\$;

create or replace function repairshop_private.validate_customer_names()
returns trigger language plpgsql security definer set search_path = ''
as \$\$
begin
  -- External sign-in can create an incomplete row before profile completion.
  -- Existing legacy names remain untouched until that field is changed.
  if (tg_op = 'INSERT' and nullif(pg_catalog.btrim(new.first_name), '') is not null)
      or (tg_op = 'UPDATE' and new.first_name is distinct from old.first_name) then
    if not repairshop_private.customer_name_is_valid(new.first_name) then
      raise exception 'Enter a valid first name.'
        using errcode = '23514', constraint = 'customer_first_name_valid';
    end if;
    new.first_name := repairshop_private.normalize_customer_name(new.first_name);
  end if;
  if (tg_op = 'INSERT' and nullif(pg_catalog.btrim(new.last_name), '') is not null)
      or (tg_op = 'UPDATE' and new.last_name is distinct from old.last_name) then
    if not repairshop_private.customer_name_is_valid(new.last_name) then
      raise exception 'Enter a valid last name.'
        using errcode = '23514', constraint = 'customer_last_name_valid';
    end if;
    new.last_name := repairshop_private.normalize_customer_name(new.last_name);
  end if;
  return new;
end;
\$\$;

drop trigger if exists validate_customer_names on public.customers;
create trigger validate_customer_names
  before insert or update of first_name, last_name on public.customers
  for each row execute function repairshop_private.validate_customer_names();

create or replace function repairshop_private.validate_auth_customer_names()
returns trigger language plpgsql security definer set search_path = ''
as \$\$
declare v_key text; v_value text;
begin
  foreach v_key in array array['first_name', 'last_name'] loop
    v_value := new.raw_user_meta_data ->> v_key;
    if (tg_op = 'INSERT' and nullif(pg_catalog.btrim(v_value), '') is not null)
        or (tg_op = 'UPDATE' and v_value is distinct from (old.raw_user_meta_data ->> v_key)) then
      if not repairshop_private.customer_name_is_valid(v_value) then
        raise exception 'Enter a valid first and last name.'
          using errcode = '23514', constraint = 'customer_name_valid';
      end if;
      new.raw_user_meta_data := pg_catalog.jsonb_set(
          new.raw_user_meta_data, array[v_key],
          pg_catalog.to_jsonb(repairshop_private.normalize_customer_name(v_value)));
    end if;
  end loop;
  return new;
end;
\$\$;

drop trigger if exists validate_auth_customer_names on auth.users;
create trigger validate_auth_customer_names
  before insert or update of raw_user_meta_data on auth.users
  for each row execute function repairshop_private.validate_auth_customer_names();

''';
  final profile = File(
    'supabase/migrations/202610090001_complete_customer_profile.sql',
  ).readAsStringSync();
  final start = profile.indexOf(
    'create or replace function public.complete_customer_profile',
  );
  final end = profile.indexOf('-- Only this validated operation');
  var completion = profile.substring(start, end);
  completion = completion.replaceFirst(
    '  -- Serialize concurrent first-time requests for this verified auth identity.',
    '''  if not repairshop_private.customer_name_is_valid(p_first_name) or
      not repairshop_private.customer_name_is_valid(p_last_name) then
    raise exception 'Enter a valid first and last name.'
      using errcode = '23514', constraint = 'customer_name_valid';
  end if;

  -- Serialize concurrent first-time requests for this verified auth identity.''',
  );
  completion = completion.replaceAll(
    'btrim(p_first_name)',
    'repairshop_private.normalize_customer_name(p_first_name)',
  );
  completion = completion.replaceAll(
    'btrim(p_last_name)',
    'repairshop_private.normalize_customer_name(p_last_name)',
  );
  final footer = '''
revoke all on all functions in schema repairshop_private from public, anon, authenticated;
revoke all on function public.complete_customer_profile(text, text, text) from public, anon;
grant execute on function public.complete_customer_profile(text, text, text) to authenticated;

commit;
''';
  final target = File(
    'supabase/migrations/202610090003_customer_name_validation.sql',
  );
  target.writeAsStringSync('$header$completion$footer');
  stdout.writeln('Generated ${target.path} (${target.lengthSync()} bytes).');
}
